# SPDX-License-Identifier: ice License 1.0

dvm:
  tls-cert: |
    -----BEGIN CERTIFICATE-----
    MIID0TCCArmgAwIBAgIUJ66CoEOD8Ud1CJpgmxdw+zgx+uEwDQYJKoZIhvcNAQEL
    BQAwbTEYMBYGA1UEAwwPbG9jYWxob3N0LmxvY2FsMQswCQYDVQQGEwJVUzERMA8G
    A1UEBwwIWW91ckNpdHkxEjAQBgNVBAgMCVlvdXJTdGF0ZTEdMBsGA1UECgwURXhh
    bXBsZS1DZXJ0aWZpY2F0ZXMwHhcNMjQxMDI1MDg1NDIxWhcNMjYxMDI1MDg1NDIx
    WjBtMRgwFgYDVQQDDA9sb2NhbGhvc3QubG9jYWwxCzAJBgNVBAYTAlVTMREwDwYD
    VQQHDAhZb3VyQ2l0eTESMBAGA1UECAwJWW91clN0YXRlMR0wGwYDVQQKDBRFeGFt
    cGxlLUNlcnRpZmljYXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AOJqJlbncScX8311xIj3EJQ4HJs9bGIfbfZIVJq2s8Cc+Mx6Ze7GU9c/eeH3q8/F
    nmfl3pjH+3UEOxmu3nR0oJLephLaNDSsVNjjo3P0ExEBr7SaKVpASPvNN3NzKgD2
    qOPOZODFGbws9raUk0GxoEWdTRkMDlgs9tc02fUvzHvxTuWqFV5dGdbASjHVqPtz
    MvtY37byrBxQuWLgfir9kxKvgqGhtiXd92+Y5DJ0HJ2E6gcU8yL3GraLDi5PqdiL
    xtfxBGHYaOwTuQK8uJdZJq3r3goWExImwwpUGDIy5TGqKvV6bW/FWf2b4P3nhNtt
    6nLxwxHNLS1YqltUnn2U/RECAwEAAaNpMGcwHQYDVR0OBBYEFNJwFyBrOgJxT3Tw
    oFz0OC5Q850/MB8GA1UdIwQYMBaAFNJwFyBrOgJxT3TwoFz0OC5Q850/MA8GA1Ud
    EwEB/wQFMAMBAf8wFAYDVR0RBA0wC4IJbG9jYWxob3N0MA0GCSqGSIb3DQEBCwUA
    A4IBAQAz7xU4mu2IY6pFq9eT+9UXTVkl4LDI+oJrc8bIdmtm2nCaseNT4ys8rfLz
    Fkp6PgDazO5ysRTtiu8XR8JfrxkkUUZvfs30nVwi3JHsUQ4kAyUwcSCMuR6IpK59
    wjclTVV6t3S1phbbVT7kpdPTVxAHHL7wvEdb26KU45o8abXmaW/zXrdVkdvY/gVx
    nSsmZGcs0hGXr2tKY317rDioFXIiVJQi+aD74cJaQmGh01H2fbSSKPYne8nHdUjD
    DJ3nUZjYQEBhd7+KllKkIOvCwnsHDDejl+M3nBUV1cax3rNinX6XA6ifWdi/m9BT
    A6iTj8nve86vgG0h2Sa4689Qd8kF
    -----END CERTIFICATE-----
  tls-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDiaiZW53EnF/N9
    dcSI9xCUOBybPWxiH232SFSatrPAnPjMemXuxlPXP3nh96vPxZ5n5d6Yx/t1BDsZ
    rt50dKCS3qYS2jQ0rFTY46Nz9BMRAa+0milaQEj7zTdzcyoA9qjjzmTgxRm8LPa2
    lJNBsaBFnU0ZDA5YLPbXNNn1L8x78U7lqhVeXRnWwEox1aj7czL7WN+28qwcULli
    4H4q/ZMSr4KhobYl3fdvmOQydBydhOoHFPMi9xq2iw4uT6nYi8bX8QRh2GjsE7kC
    vLiXWSat694KFhMSJsMKVBgyMuUxqir1em1vxVn9m+D954Tbbepy8cMRzS0tWKpb
    VJ59lP0RAgMBAAECggEAB3CFotCMhoRnibK4sD0ZWZwauTF0Z1NROD40r3e7jM5A
    8OvAVS9FmnqZYpF83wEcknKPv5/p6on8Iid9jkCLH9WlNH810hmWg8uTt5qTFM7k
    IIWklbSr4UA4kfh8WRdBweh/0Ts7Zv7oOrluOZf1+aDwo1ci0oa5s/pmg1ixz0xf
    oP3NapHhEArfcFGvbxxQ6Ro2c3uZ100ARlf3BPPtXIasCTPCPCqGn9LLDkbsfTXz
    NEKbqOxyAnJusnE2fCj4asKCJCmKeyCzuszhWiH/tT93tZpsj0WBQmKXF3BNinrn
    bwg6Gp7enbhydYDuZ2Mj0XcKz42kOWHBYCPhyX+kcQKBgQDyAZLG3yW73uHmXI45
    sx6mKNpf63p8JZQsMKW4Ve/wR9xatvS+kxvOIGtOxsQbzx1kgkeF8B9LPWROfRTa
    TGwEKFFOdNSNOU6AcOodWb+PCgRZy/0Zfer4zFqlEPt9I07O+6aaUqGN8qMGOdKq
    8AcpCT/aHR632hesoCfteKKBmQKBgQDvgcZcGCGbJEnNEcPGFv6lcLW7mS077tR1
    GgdVXu6C3lE7ShePpo+LBH22vRLj6YGs8UEHIrjepzwH+hMklQQFui70OpU+CtHM
    tvW6PLxp5C2fKSECfd3KjWebAsaSNxmUMb3lECpHEuZd93sR7xnvHrexRMDfJW2A
    UHpmDzByOQKBgEezUaJcUNi1s2ZF+9l6iVUfe3u5z8NieuEQ1LiltX4SPGYgGKkx
    +qX6kvB3EXlPxtyVgM1dFFh9au+aPYhj5gjhTR2anbLtzKVfTu29PnUJubpFJsrb
    tLdcDGslee1cfafzhSvp2XWt8sEQdqswjF6LIADmach89FCv7sR73mHZAoGBAIWW
    ctcnNodcBDX3dKTman5IkXTjiRFmsuXl8LUzUAF6kwBo4R9knafCh4QHjaPFuGiH
    3+dk/Ixj5t3kJA1BeI7hPBNJIbkLO93dJs4L1mORu8iMnjbPkYfKu0EAmVUwmnnI
    DMzY6VvfNNKwmNp17JctIPQlDxbnv13UhZCrZDAxAoGBAI3/G2nPUW/IayvgpdeD
    4AAIP4Q+QPNqsN6fJKFFmyabrJCLVEdOE00Upl/9QF7uaGZ/5s1gXSZ9kBVQ6g4z
    LEmxIHOYAtmTwLwU+eKFs/3gjVUxSBg4AA0h1Ox/gjA6Hb+aNZHapPW8XH+jF6Ij
    RK3+I8t8OXWV3eiFcVaUGUlc
    -----END PRIVATE KEY-----
  private-key: 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
  relay-url: "wss://example.com"
