# SPDX-License-Identifier: ice License 1.0

validation:
  max-wrapped-event-expiration: 720h

database:
  query:
    url: "file::memory:?cache=shared"
    private-key: 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
    relay-url: "wss://example.com"
