# SPDX-License-Identifier: ice License 1.0

push-notifications:
  fcm-credentials-path: /dev/null

validation:
  relay-url: wss://relay.example.com

database/query:
  relay-url: wss://relay.example.com
  private-key: private-key
