# SPDX-License-Identifier: ice License 1.0

push-notifications:
  fcm-credentials-file: /dev/null
  fcm-android-configs:
    - {}
  fcm-ios-configs:
    - {}
  fcm-web-configs:
    - {}
  private-key: 97da572f75c23bff475bc48cd3ff193a0681e82907fb97d0a2d44ec1f0fb88b1b88d40e358e8264a3b9ca2a6abc0ba7bd2035d1647af7acdb211f4a3dccab44e
  relay-url: wss://relay.example.com

validation:
  relay-url: wss://relay.example.com

database/query:
  relay-url: wss://relay.example.com
  private-key: private-key
