# SPDX-License-Identifier: ice License 1.0

database/command:
  debug: true
  discovery-port: 19966
  absolute-node-private-key-path: "./../database/command/.testdata/node_key2.json"
  absolute-root-path: "../../.cometbft3"

database/query:
  private-key: "eff8260efe5ffe4a73a757d794e673d7497a16621ab7efb387446c65ec8488a9"
  url: "postgresql://root:pass@localhost:5439/subzero"
  relay-url: wss://localhost