-- SPDX-License-Identifier: ice License 1.0

DROP TABLE IF EXISTS old_events;
DROP TABLE IF EXISTS old_event_tags;
DROP TABLE IF EXISTS old_events_search;
--------
DROP INDEX IF EXISTS replaceable_event_uk;
DROP INDEX IF EXISTS parameterized_replaceable_event_uk;
DROP INDEX IF EXISTS idx_events_system_created_at;
DROP INDEX IF EXISTS idx_events_kind_system_created_at;
DROP INDEX IF EXISTS idx_events_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_master_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_kind_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_kind_master_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_id_kind_system_created_at;
DROP INDEX IF EXISTS idx_events_id_created_at_system_created_at;
DROP INDEX IF EXISTS idx_events_id_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_id_master_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_id_kind_pubkey_created_at_system_created_at;
DROP INDEX IF EXISTS idx_events_id_kind_master_pubkey_created_at_system_created_at;
DROP INDEX IF EXISTS idx_events_system_created_at_id_created_at;
DROP INDEX IF EXISTS idx_events_reference_id_system_created_at;
DROP INDEX IF EXISTS idx_events_pubkey_master_pubkey_system_created_at;
DROP INDEX IF EXISTS idx_events_reference_id;
DROP INDEX IF EXISTS idx_event_tags_key_value1;
DROP INDEX IF EXISTS idx_event_tags_key_value1_expiration;
DROP INDEX IF EXISTS idx_event_tags_key_value2;
DROP INDEX IF EXISTS idx_event_tags_key_value3;
DROP INDEX IF EXISTS idx_event_tags_id_key_value2;
DROP INDEX IF EXISTS idx_event_tags_id_key_value1_value2;
DROP INDEX IF EXISTS idx_event_tags_id_key_value1_value3;
DROP INDEX IF EXISTS idx_event_tags_id_key_value1_value2_value3;
DROP INDEX IF EXISTS idx_event_counters_reference_id;
--------
drop   trigger if     exists trigger_events_after_insert_generate_tags;
drop   trigger if     exists trigger_events_before_update_remove_old_data;
drop   trigger if     exists trigger_events_after_update_generate_tags;
drop   trigger if     exists trigger_events_before_insert_unwind_repost;
drop   trigger if     exists trigger_events_after_insert_link_repost;
drop   trigger if     exists trigger_events_before_insert_check_onbehalf_permission;
drop   trigger if     exists trigger_events_before_update_check_attestation_list_content;
drop   trigger if     exists trigger_events_before_delete_remove_tags_explicit;
drop   trigger if     exists trigger_event_tags_after_insert_inc_counter;
drop   trigger if     exists trigger_event_tags_after_delete_dec_counter;
drop   trigger if     exists trigger_events_after_insert_search_index;
drop   trigger if     exists trigger_events_after_delete_search_index;
