logger:
  encoder: console
  level: debug
echo:
  host: localhost:9999
  version: test
  development: true
  wsServer:
    port: 9999
    certPath: fixture/.testdata/localhost.crt
    keyPath: fixture/.testdata/localhost.key
pubsub:
  host: localhost:9998
  version: test
  development: true
  wsServer:
    port: 9998
    certPath: fixture/.testdata/localhost.crt
    keyPath: fixture/.testdata/localhost.key