name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up latest Go version
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: go build -v -tags "linux sqlite_stat4 sqlite_icu" ./...

    - name: Test
      run: go test -tags "linux sqlite_stat4 sqlite_icu" -timeout 20m -tags=test -v -cover -coverprofile=cover.out -covermode atomic ./...
